version: '2'

services:
  # nginx:
  #   image: jwilder/nginx-proxy
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - front-trier
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
  #     - ./certs:/etc/nginx/certs:ro
  #     - ./vhost.d:/etc/nginx/vhost.d
  #     - /usr/share/nginx/html

  # letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./certs:/etc/nginx/certs:rw
  #   networks:
  #     - front-trier
  #   volumes_from:
  #     - nginx
  #   depends_on:
  #     - nginx

  wordpress:
    image: wordpress:4.9
    # restart: always
    environment:
      # - VIRTUAL_HOST=example.org
      # - LETSENCRYPT_HOST=example.org
      # - LETSENCRYPT_EMAIL=example@mail.example.org
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_PASSWORD=WEig3MNl
    ports:
      - "8080:80"
    # expose:
       # - 80
    networks:
      - front-trier
      - back-trier
    volumes:
      - wp-html:/var/www/html:rw
    depends_on:
       - db
       # - nginx

  db:
    image: mariadb:10
    # restart: always
    networks:
      - back-trier
    volumes:
      - db-data:/var/lib/mysql:rw
    environment:
      # Change default PW for actual deployment!
      - MYSQL_ROOT_PASSWORD=WEig3MNl

networks:
  front-trier: {}
  back-trier: {}

volumes:
  wp-html: {}
  db-data: {}
